version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    environment:
      TZ: Asia/Istanbul
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://username:password@mongo:27017/

  # nextjs:
  #   build: .
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     mongo:
  #       condition: service_healthy

volumes:
  mongo-data:
